### ISSUE TITLE
How to get in to Dev mode ?

### ISSUE THREAD

**Issue by singlag** [droner69/MavicPro#1]
How to get in to Dev mode ?
I tried set debug to t.r.u.e in \AppData\Roaming\DJIAssistant2\Local Storage\file__0.localstorage by sqlite,  set to read-only and run "DJI Assistant 2.exe" --debugger /  "DJI Assistant 2.exe" --factory
but no luck

**Comment by dave-pitman** [comment]
@singlag 
Here is a video tutorial on how to enable dev mode in Assistant 2

https://youtu.be/CkpfC56u_ak
