### ISSUE TITLE
Extracting FW and what to do with it

### ISSUE THREAD

**Issue by dave-pitman** [droner69/MavicPro#2]
@droner69 
Sorry,  I'm just using the Issue tab as a messaging device.  :(

I don't have a Mavic,  but have a P4P.  I am interested in learning how to extract (save) the loaded FW as well as how to then load extracted FW.  I don't know if you have these skills or not,  but if you do,  it would be great if you could reach out to me.  I've tried to find answers on FB and RCG where there are active discussions on activating development mode in the Assistant 2 software (which I have done).  But no info on how to actually save and load various FW.

Anyway,  Thank you and hope to hear from you whether you know how or just to say you do not.

Dave Pitman
davpitman(at)gmail.com

**Comment by droner69** [comment]
I am not familiar with the P4P, so I would not be the right person ask.

When upgrading through Assistant, the firmware packages that are downloaded can be found at "/Applications/Assistant.app/Contents/MacOS/Data/firm_cache" using Mac or "C:\Program Files (x86)\DJI Product\DJI Assistant 2\ Assistant\Data\firm_cache" using Windows.

Again, I'm not sure about P4P, but on the Mavic they can also be found at "ftp://192.168.42.2/upgrade/upgrade/backup/"

For extraction, you may could use binwalk or fvantienen's tools.
